# Site settings
title: Gopikrishna Arepalli
email: a.gopikrishna01@gmail.com
author: Gopikrishna Arepalli
description:
baseurl: ""
url: "https://gopikrishna-a.github.io/"

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: gopikrishna-a
facebook_username: gopikrishna.arepalli
google_plus_username: +GopikrishnaArepalli
linkedin_username: GopikrishnaArepalli
pinterest_username: agopikrishna01

# plugins
plugins: [jekyll-paginate]
#No of post per page
paginate: 5

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: my_disqus_shortname