# Site settings
title:
email: a.gopikrishna01@gmail.com
author:
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: gopikrishna-a
facebook_username: gopikrishna.arepalli
google_plus_username: +GopikrishnaArepalli
linkedin_username: gopikrishna-a
pinterest_username: agopikrishna01

# plugins
plugins: [jekyll-paginate]
#No of post per page
paginate: 3